sudo: required

services:
  - docker

language: php
php:
  - 7.2
  - 7.3

env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=files_external_ftp
    - DB=sqlite
  matrix:
#    - FTPD=pure-ftpd
    - FTPD=proftpd
    - FTPD=vsftpd

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - mkdir /tmp/ftp
  - chmod 0777 /tmp/ftp
  - if [[ "$FTPD" == 'proftpd' ]]; then docker run --name ftp -d --net host -e FTP_USERNAME=test -e FTP_PASSWORD=test -v /tmp/ftp:/home/test hauptmedia/proftpd; fi
  - if [[ "$FTPD" == 'vsftpd' ]]; then docker run --name ftp -d --net host -e FTP_USER=test -e FTP_PASS=test -v /tmp/ftp:/home/vsftpd/test fauria/vsftpd; fi

  - cd ../
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH nextcloud
  - mv $APP_NAME nextcloud/apps/

before_script:
  # fill nextcloud with default configs and enable the app
  - cd nextcloud
  - mkdir data
  - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database sqlite --database-pass=''
  - ./occ app:enable $APP_NAME

script:
  # Run phpunit tests
  - cd apps/$APP_NAME/tests
  - echo '{"host":"localhost","user":"test","password":"test"}' > config.json
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover clover.xml

matrix:
  fast_finish: true
